<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\NewFolder\**" />
    <Content Remove="Views\NewFolder\**" />
    <EmbeddedResource Remove="Views\NewFolder\**" />
    <None Remove="Views\NewFolder\**" />
    <TypeScriptCompile Remove="Views\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\Home\Menu.cshtml.cs" />
    <Compile Remove="Views\Ventas\NuevaVenta.cshtml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\Home\Menu.cshtml" />
    <Content Remove="Views\Ventas\Index1.cshtml" />
    <Content Remove="Views\Ventas\NuevaVenta.cshtml" />
    <Content Remove="wwwroot\about.html" />
    <Content Remove="wwwroot\menu.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

</Project>
